//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string Director { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Thumbnail { get; set; }
        public string Description { get; set; }
    }
}
